"""added timers to recipe instructions

Revision ID: 02ec5b3e0525
Revises: 3897397b4631
Create Date: 2024-11-05 15:28:40.528380

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "02ec5b3e0525"
down_revision: str | None = "3897397b4631"
branch_labels: str | tuple[str, ...] | None = None
depends_on: str | tuple[str, ...] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timers_json", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_instructions", schema=None) as batch_op:
        batch_op.drop_column("timers_json")

    # ### end Alembic commands ###
